<a href="https://colab.research.google.com/github/npasuparthi/nagendra-AI_ML/blob/master/Copy_of_Questions_R6_INNDL_Labs_Nagendra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [ ]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.4.1


### Set random seed

In [ ]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [ ]:
features = iris.data
labels = iris.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.25, random_state=44)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [ ]:
y_train = tf.keras.utils.to_categorical(y_train, num_classes=3)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=3)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [ ]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [ ]:
model.add(tf.keras.layers.InputLayer(input_shape=(4,)))

In [ ]:
#Add output layer
model.add(tf.keras.layers.Dense(3, activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [ ]:
sgd_optimizer = tf.keras.optimizers.SGD(learning_rate=1)

In [ ]:
#Compile the model
model.compile(optimizer=sgd_optimizer, loss='categorical_crossentropy', 
              metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [ ]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [ ]:
model_checkpoint = tf.keras.callbacks.ModelCheckpoint('NP_iris.h5', save_best_only=True, monitor='val_accuracy', mode='max', verbose=1)

In [ ]:
model.fit(X_train, y_train,          
          validation_data=(X_test,y_test),
          epochs=100,
          batch_size=32, 
          callbacks=[model_checkpoint])

Epoch 1/100
4/4 [==============================] - 0s 65ms/step - loss: 12.8087 - accuracy: 0.3612 - val_loss: 23.8650 - val_accuracy: 0.3158

Epoch 00001: val_accuracy improved from -inf to 0.31579, saving model to NP_iris.h5
Epoch 2/100
4/4 [==============================] - 0s 16ms/step - loss: 22.5876 - accuracy: 0.2741 - val_loss: 4.2484 - val_accuracy: 0.6842

Epoch 00002: val_accuracy improved from 0.31579 to 0.68421, saving model to NP_iris.h5
Epoch 3/100
4/4 [==============================] - 0s 14ms/step - loss: 5.8080 - accuracy: 0.6942 - val_loss: 4.0101 - val_accuracy: 0.6842

Epoch 00003: val_accuracy did not improve from 0.68421
Epoch 4/100
4/4 [==============================] - 0s 15ms/step - loss: 8.0609 - accuracy: 0.6472 - val_loss: 4.0230 - val_accuracy: 0.6842

Epoch 00004: val_accuracy did not improve from 0.68421
Epoch 5/100
4/4 [==============================] - 0s 15ms/step - loss: 4.8079 - accuracy: 0.7199 - val_loss: 5.1869 - val_accuracy: 0.6842

Epoch 00005

## Question 10

### Make predictions
- Predict labels on one row

In [ ]:
import numpy as np
pred = model.predict(np.expand_dims(X_test[0], axis=0))

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [ ]:
# predicted class
np.argmax(pred)

2

In [ ]:
# actual class
y_test[0]

array([0., 0., 1.], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [ ]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.4.1


### Set random seed

In [ ]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [ ]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

{}

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [ ]:
import pandas as pd
prices = pd.read_csv('prices.csv')

In [ ]:
prices.drop(['date', 'symbol'], axis=1, inplace=True)

In [ ]:
prices.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [ ]:
prices_1000 = prices.head(1000)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [ ]:
features = prices_1000[['open', 'close', 'low', 'high']]

In [ ]:
features.head()

open       close         low        high
0  123.430000  125.839996  122.309998  126.250000
1  125.239998  119.980003  119.940002  125.540001
2  116.379997  114.949997  114.930000  119.739998
3  115.480003  116.620003  113.500000  117.440002
4  117.010002  114.970001  114.089996  117.330002

In [ ]:
label = prices_1000[['volume']]

In [ ]:
label.head()

volume
0  2163600.0
1  2386400.0
2  2489500.0
3  2006300.0
4  1408600.0

In [ ]:
label = label/1000000

In [ ]:
label.head()

volume
0  2.1636
1  2.3864
2  2.4895
3  2.0063
4  1.4086

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [ ]:
features_np= features.to_numpy(dtype='float32')
label_np = label.to_numpy(dtype='float32')


## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [ ]:
features_norm = tf.math.l2_normalize(features_np)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [ ]:
W = tf.zeros(4,1)

In [ ]:
W

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

In [ ]:
b = tf.zeros(1,1)

In [ ]:
b.shape

TensorShape([1])

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [ ]:
def myPred(X, W, b):
  xw_matmul = tf.matmul(X, W)
  y = tf.add(xw_matmul, b)
  return y

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [ ]:
def myLoss(Y, YPred):  #rmse = (y-ybar)^2/n
    return tf.reduce_mean(tf.square(Y - YPred))

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [ ]:
def myTrain(X_train, y_train, W, b, learning_rate=0.01 ):
  with tf.GradientTape() as tape:
    tape.watch([W,b])
    current_pred = myPred(X_train, W,b)
    current_loss = loss(y_train, current_pred)
  dW, db = tape.gradient(current_loss,[w, b])
  W = W - learning_rate*dW
  b = b - learning_rate*db

  return W, b


## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [ ]:
for j in range(100):
  W,b=myTrain(features_norm, label_np, W,b)

InvalidArgumentError: ignored

In [ ]:
features_norm

<tf.Tensor: shape=(1000, 4), dtype=float32, numpy=
array([[0.02202893, 0.02245905, 0.02182904, 0.02253223],
       [0.02235197, 0.0214132 , 0.02140606, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051191, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.00799559, 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

### Observe values of Weight
- Print the updated values

### Observe values of Bias
- Print the updated values