<a href="https://colab.research.google.com/github/npasuparthi/nagendra-AI_ML/blob/master/R7_Lab_questions_NNDL_Nagendra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="http://drive.google.com/uc?export=view&id=1tpOCamr9aWz817atPnyXus8w5gJ3mIts" width=500px>

## Lab on NNDL Part 1: Tensorflow Basic

### Tensors

Tensors are multi-dimensional arrays with a uniform type

##Question 1


### Create a rank-0 tensor
- A "scalar" is called "rank-0" tensor
- the tensor should contain value 99.99

In [2]:
import tensorflow as tf


In [10]:
rank_0 = tf.constant(99.99)
rank_0

<tf.Tensor: shape=(), dtype=float32, numpy=99.99>

### Create a rank-1 tensor

- A "vector" (list) is called "rank-1" tensor [9,8,7,6,5]
- A vector has one axis

In [12]:
rank_1 = tf.constant([9,8,7,6,5])
rank_1

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([9, 8, 7, 6, 5], dtype=int32)>

### Add 7 to all the elements of the above created tensor
- Use Broadcasting

In [17]:
print(tf.add(rank_1, [7]))
print(rank_1 + 7)

tf.Tensor([16 15 14 13 12], shape=(5,), dtype=int32)
tf.Tensor([16 15 14 13 12], shape=(5,), dtype=int32)


### Create a rank-2 tensor
[[1, 2, 3], [ 4,5,6]]
- A "matrix"  "is called rank-2" tensor
- It has 2 axes

In [19]:
rank_2 = tf.constant([[1,2,3],[4,5,6]])
rank_2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

### Change the shape of the above created tensor to shape (3,2)

In [22]:
tf.reshape(rank_2, [3,2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [23]:
tf.reshape(rank_2, [-1,2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

### Check the dtype, number of axes and the shape of tensor

In [31]:
print(rank_2.dtype)
print(rank_2.ndim)
print(rank_2.shape)

<dtype: 'int32'>
2
(2, 3)


- Tensors can have more axes, like rank-3 or rank-4 tensor

##Lab on NNDL Part 2: Cars selling price prediction

### Data Set -
Domain: Finance, Business 
Data: https://www.kaggle.com/nehalbirla/vehicle-dataset-from-cardekho?select=Car+details+v3.csv

The data contains various features of used cars.

#### Features

1. year

2. selling_price: Price at which it was sold (**Target Feature**)

3. km_driven

4. fuel

5. seller_type

6. transmission

7. Owner

8. mileage

9. engine

10. max_power

11. seats

 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

##Objective

Predict the selling price of used cars based on the given features

## Steps to perform:

#### 1. Import important Libraries
#### 2. Import Dataset and exploration
#### 3. Data Pre-processing
#### 4. Training a Neural Network Model
#### 5. Evaluating the model
#### 6. Conclusion


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


### Import important libraries

In [187]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

## Question 1

### Load the data
- Load the data, check the shape of data

In [188]:
df = pd.read_csv('/content/car_data-1.csv')

In [189]:
df.head()

year  selling_price  km_driven  ...   engine   max_power seats
0  2014         450000     145500  ...  1248 CC      74 bhp   5.0
1  2014         370000     120000  ...  1498 CC  103.52 bhp   5.0
2  2006         158000     140000  ...  1497 CC      78 bhp   5.0
3  2010         225000     127000  ...  1396 CC      90 bhp   5.0
4  2007         130000     120000  ...  1298 CC    88.2 bhp   5.0

[5 rows x 11 columns]

In [190]:
df.shape

(8128, 11)

## Question 2

### Preprocess the data
- Convert mileage, engine and max_power to numerical by extract numerical values from the strings
- Label Encode: 'owner' column
- One Hot Encode: 'fuel','seller_type','transmission' columns
- Drop all the instances with null values

In [191]:
def map_num(num):
    try:
        if type(num) == str:
            return float(num.split()[0])
        else:
            return num
    except:
        return np.nan


In [192]:
df[['mileage','engine','max_power']] = df[['mileage','engine','max_power']].applymap(map_num)


In [193]:
df.head()

year  selling_price  km_driven    fuel  ... mileage  engine max_power  seats
0  2014         450000     145500  Diesel  ...   23.40  1248.0     74.00    5.0
1  2014         370000     120000  Diesel  ...   21.14  1498.0    103.52    5.0
2  2006         158000     140000  Petrol  ...   17.70  1497.0     78.00    5.0
3  2010         225000     127000  Diesel  ...   23.00  1396.0     90.00    5.0
4  2007         130000     120000  Petrol  ...   16.10  1298.0     88.20    5.0

[5 rows x 11 columns]

In [194]:
o = {'First Owner':1, 'Second Owner':2, 'Third Owner':3,
       'Fourth & Above Owner':4, 'Test Drive Car':5}
df['owner'] = df['owner'].map(o)
df.head()


year  selling_price  km_driven    fuel  ... mileage  engine  max_power  seats
0  2014         450000     145500  Diesel  ...   23.40  1248.0      74.00    5.0
1  2014         370000     120000  Diesel  ...   21.14  1498.0     103.52    5.0
2  2006         158000     140000  Petrol  ...   17.70  1497.0      78.00    5.0
3  2010         225000     127000  Diesel  ...   23.00  1396.0      90.00    5.0
4  2007         130000     120000  Petrol  ...   16.10  1298.0      88.20    5.0

[5 rows x 11 columns]

In [195]:
from  sklearn.preprocessing import OneHotEncoder
ohe= OneHotEncoder(sparse=False, dtype=np.int64)
cat_col = ['fuel', 'seller_type', 'transmission']
z=ohe.fit_transform(df[cat_col])
encoded_data = pd.DataFrame(z,columns=ohe.get_feature_names(cat_col))
encoded_data.head()

fuel_CNG  fuel_Diesel  ...  transmission_Automatic  transmission_Manual
0         0            1  ...                       0                    1
1         0            1  ...                       0                    1
2         0            0  ...                       0                    1
3         0            1  ...                       0                    1
4         0            0  ...                       0                    1

[5 rows x 9 columns]

In [196]:
df1=df.drop(columns=cat_col, axis=1)
final_df = pd.concat([df1, encoded_data], axis=1)
final_df.head()

year  selling_price  ...  transmission_Automatic  transmission_Manual
0  2014         450000  ...                       0                    1
1  2014         370000  ...                       0                    1
2  2006         158000  ...                       0                    1
3  2010         225000  ...                       0                    1
4  2007         130000  ...                       0                    1

[5 rows x 17 columns]

In [197]:
final_df.dropna(inplace=True)


## Question 3

### Split the data and then scale the data
- Split the data into ratio of 75:25 with random state=12
- Perform standard scaling on X_train and X_test data


In [198]:
X = final_df.drop('selling_price', axis=1)
y = final_df['selling_price']


In [199]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=12)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

((5929, 16), (1977, 16), (5929,), (1977,))

In [200]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train_sc = sc.fit_transform(x_train)
x_test_Sc = sc.transform(x_test)


## Question 4

### Create a Deep Neural Network Model for Regression
- Initialize a Sequential model
- Add 3 hidden layer with activation relu (Number of neurons = 64,128,32 respectively)
- Add dropout layer after each hidden layer
- Add a Dense layer with one neuron as output, use activation linear
  


In [201]:
tf.keras.backend.clear_session()
model = tf.keras.models.Sequential()

from tensorflow.keras.layers import Flatten, Dense, Input, BatchNormalization

model=tf.keras.Sequential()
model.add(tf.keras.Input(shape=(16)))
model.add(tf.keras.layers.BatchNormalization())

In [202]:
from tensorflow.keras.layers import Flatten, Dense, Input, BatchNormalization
from keras.utils.vis_utils import plot_model

### Check model summary and visualize the model

In [203]:
#Hidden layers
model.add(tf.keras.layers.Dense(64, activation='relu', name='Layer_1'))
model.add(tf.keras.layers.BatchNormalization())
#Dropout layer
model.add(tf.keras.layers.Dropout(0.15))


model.add(tf.keras.layers.Dense(128, activation='relu', name='Layer_2'))
model.add(tf.keras.layers.BatchNormalization())
#Dropout layer
model.add(tf.keras.layers.Dropout(0.10))

#Hidden layers
model.add(tf.keras.layers.Dense(32, activation='relu', name='Layer_3'))
model.add(tf.keras.layers.BatchNormalization())
#Dropout layer
model.add(tf.keras.layers.Dropout(0.05))


#Output layer
model.add(tf.keras.layers.Dense(1, activation='linear', name='Output'))

In [204]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
batch_normalization (BatchNo (None, 16)                64        
_________________________________________________________________
Layer_1 (Dense)              (None, 64)                1088      
_________________________________________________________________
batch_normalization_1 (Batch (None, 64)                256       
_________________________________________________________________
dropout (Dropout)            (None, 64)                0         
_________________________________________________________________
Layer_2 (Dense)              (None, 128)               8320      
_________________________________________________________________
batch_normalization_2 (Batch (None, 128)               512       
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)              

## Question 5

### Compile the model

- Compile the model
- Use "adam" optimizer
- for calculating loss, use mean absolute error
- use R2 score (coefficient of determination) as the metric

In [205]:
from keras import backend as K
def r_2_Score(y_true, y_pred):
  SS_resid = K.sum(K.square(y_true-y_pred))
  SS_total = K.sum(K.square(y_true-K.mean(y_true)))
  return (1-SS_resid/(SS_total+ K.epsilon()))

In [206]:
opt = tf.keras.optimizers.Adam(learning_rate=0.01)

model.compile(optimizer=opt, loss='mean_absolute_error', metrics=[r_2_Score])

In [207]:
callback=tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True, mode='min')

Other metrics can also be used to track the learning of the model:

To learn different metrics for classification and regression visit the following link:

Link: https://keras.io/api/metrics/#usage-with-compile-amp-fit

### Train your model

- epochs: 1000
- batch size: 32
- Use test data as validation data
- Also add callback, such that if validation loss doesn't decreases consecutively 10 times, stop the training and return the weights for the previous best model

In [208]:
#Train the model
history = model.fit(x_train_sc,y_train,
          validation_data=(x_test_Sc,y_test),
          epochs=100,
          batch_size=32,
          verbose=1)

Epoch 1/100
186/186 [==============================] - 2s 5ms/step - loss: 638857.0137 - r_2_Score: -1.1929 - val_loss: 654007.5000 - val_r_2_Score: -1.0343
Epoch 2/100
186/186 [==============================] - 1s 5ms/step - loss: 648082.0287 - r_2_Score: -1.1187 - val_loss: 653164.4375 - val_r_2_Score: -1.0314
Epoch 3/100
186/186 [==============================] - 1s 5ms/step - loss: 647349.6166 - r_2_Score: -1.1156 - val_loss: 651727.0625 - val_r_2_Score: -1.0261
Epoch 4/100
186/186 [==============================] - 1s 5ms/step - loss: 633943.5328 - r_2_Score: -1.1537 - val_loss: 649752.8125 - val_r_2_Score: -1.0191
Epoch 5/100
186/186 [==============================] - 1s 5ms/step - loss: 652438.2136 - r_2_Score: -1.0351 - val_loss: 647247.0000 - val_r_2_Score: -1.0101
Epoch 6/100
186/186 [==============================] - 1s 5ms/step - loss: 623191.0662 - r_2_Score: -1.3727 - val_loss: 644215.8125 - val_r_2_Score: -0.9995
Epoch 7/100
186/186 [==============================] - 1s 

## Question 6

### Evaluate the model
- Evaluate the model on test data
- Visualize the model's learning

In [209]:
#Model prediction
model.evaluate(x_test_Sc, y_test)

62/62 [==============================] - 0s 2ms/step - loss: 165275.0625 - r_2_Score: 0.7581


[165275.0625, 0.7581117749214172]

In [210]:
from sklearn.metrics import r2_score


In [211]:
y_pred = model.predict(x_test_Sc)
r2_score(y_test, y_pred)

0.7138905263050319

- Hint: The R2 score will get affected by batch size. 

**Batch Size**: Number of samples considered in one iteration

### Check the R2 score on complete test data

### Visualize model learning
- Visualize model learning using train and test r2 score
- Visualize model learning using train and test loss

##  Model tuning and Hyperparameter Tuning
## Question 7 (Optional)

### Create another Deep Neural Network Model for Regression to experiment with other hyper-parameters
- Initialize a Sequential model
- Add a batch normalization layer
- Add 3 hidden layer with activation leaky-relu (Number of neurons = 64,128,32 respectively)
- Add dropout layer after each hidden layer
- Add a Dense layer with one neuron as output, use activation linear
  


### Compile the model

- Compile the model
- Use "adam" optimizer 
- for calculating loss, use mean absolute error
- use R2 score (coefficient of determination) as the metric

### Train your model

- epochs: 1000
- batch size: 16
- Use test data as validation data
- Also add callback, such that if validation loss doesn't decreases consecutively 10 times, stop the training and return the weights for the previous best model
- Add checkpoints to save the model after every epoch


### Check the R2 score on complete test data

### Visualize model learning
- Visualize model learning using train and test r2 score
- Visualize model learning using train and test loss

### Create another Deep Neural Network Model for Regression to experiment with other hyper-parameters
- Initialize a Sequential model
- Add a batch normalization layer
- Intialize weights using HeUniform with seed = 7
- Add 4 hidden layer with activation relu (Number of neurons = 256,128,64,32 in each layer respectively)
- Add dropout layer after each hidden layer
- Add a Dense layer with one neuron as output, use activation linear
  


### Compile the model

- Compile the model
- Use "adam" optimizer with learning rate = 0.002
- for calculating loss, use mean squared error
- use R2 score (coefficient of determination) as the metric

### Train your model

- epochs: 1000
- batch size: 64
- Use test data as validation data
- Also add callback, such that if validation loss doesn't decreases consecutively 10 times, stop the training and return the weights for the previous best model



### Check the R2 score on complete test data

### Visualize model learning
- Visualize model learning using train and test r2 score
- Visualize model learning using train and test loss